# MDAnalysis Basics

In [2]:
import numpy as np
import sys, os
import math as math
import MDAnalysis as MDA

In [12]:
# Print MDAnalysis version
print(MDA.__version__)

0.19.2


In [4]:
# Pass the Arguments to the script (gro and xtc )
gro = sys.argv[1]
xtc = sys.argv[2]

In [5]:
# Define input file names
gro = "prod.gro"
xtc = "pbc.xtc"

In [7]:
print ("Given Input Files are: ", gro, "and", xtc, "\n")

Given Input Files are:  prod.gro and pbc.xtc 



# Load the Trajectory into MDA

In [8]:
# Read the trajectory 
u = MDA.Universe(gro,xtc)

In [10]:
#Get the number of frames of trajectory
num_frames = len(u.trajectory)
print ("No. of Frames:", num_frames, "\n")

No. of Frames: 2001 



In [34]:
# No of Atoms
num_Atoms = len(u.atoms)
print ("No. of Atoms: ", num_Atoms, "\n")

No. of Atoms:  2387 



In [44]:
# List the all the Atoms
#list(u.atoms)

# List the first 5 atoms
#list(u.atoms[:5])

In [17]:
# Number of Residues present
residues = len(u.atoms.residues)
print ("No. of Residues: ", residues)

No. of Residues:  789


In [19]:
# Number of Residues present
residues1 = u.atoms.n_residues
print ("No. of Residues: ", residues1)

No. of Residues:  789


In [31]:
# Get resid & Resnames 
Residues = u.atoms.residues[2]
resids = Residues.resid
resnames = Residues.resname
print ("Resid:", resids, "Resname:", resnames)

Resid: 3 Resname: ALA


# Atom Selection

In [53]:
# MDAnalysis comes with a fairly complete atom selection facility. Primarily, one uses the method 
# select_atoms() of a Universe.

protein = u.select_atoms("protein")
Protein_Atoms = len(protein)

waters = u.select_atoms("resname WAT")
waters_atoms = len(waters)

print ("No. of Protein Atoms: ",Protein_Atoms, "No. of Water Atoms: ", waters_atoms,"\n")
#list(protein)

No. of Protein Atoms:  32 No. of Water Atoms:  2355 



In [57]:
# Total Residues
residues = u.atoms.n_residues
print ("No. of Total Residues:", residues, "\n")

# No of Protein Residues
Protein_residues = len(protein.residues)
print ("No. of Protein Residues:", Protein_residues, "\n")

# No. of Water Residues
Water_residues = len(waters.residues)
print ("No. of Water Residues:", Water_residues, "\n")


No. of Total Residues: 789 

No. of Protein Residues: 4 

No. of Water Residues: 785 



In [61]:
pos = protein.positions

print (pos[:5])

[[15.130001 12.090001 11.71    ]
 [14.62     13.050001 11.620001]
 [14.14     13.380001 12.540001]
 [13.820001 12.820001 10.92    ]
 [15.500001 14.17     11.07    ]]


In [72]:
# Print BOX dimensions
box = u.dimensions
print(box[:3])

[29.685 31.109 26.227]


# Looping over trajectory

In [ ]:
# Loop over trajectory or frames
for ts in u.trajectory:
   print(ts.frame)